### ISSUE TITLE
MuJoCo Rendering Code

### ISSUE THREAD

**Issue by kevinzakka** [geng-haoran/Simulately#18]
Hello,

Thanks for making this resource public! Would you mind pointing me to the rendering code that was used for MuJoCo?

Cheers

**Comment by YuyangLee** [comment]
Hi! Our codes used in the rendering tests are in the `code` branch. You can find them [here](https://github.com/geng-haoran/Simulately/tree/code/rendering). :)

**Comment by kevinzakka** [comment]
Hi @YuyangLee, it looks like you are including the physics step in the rendering time computation for MuJoCo but not doing so for other simulators. That seems wrong unless I am misunderstanding the code.

**Comment by kevinzakka** [comment]
Obviously the sim time is cheap here but I think the benchmark should minimize differences as much as possible between simulators!

**Comment by geng-haoran** [comment]
Yes, we will update the code and the reported fps. Thank you so much for the information.

**Comment by geng-haoran** [comment]
Already updated, thank you again!
