### ISSUE TITLE
SAPIEN and ManiSkill updates (GPU parallel sim + rendering)

### ISSUE THREAD

**Issue by StoneT2000** [geng-haoran/Simulately#23]
Thank you for this nice wiki, I often point newcomers to simulation to this wiki first :)

SAPIEN and [ManiSkill](https://github.com/haosulab/ManiSkill) recently have added support for GPU parallelized (diverse) simulation of rigid bodies, as well as a parallel rendering system. We would like to include that update info on the wiki, what would be the best way to do that?

**Comment by geng-haoran** [comment]
Sure! Thank you for your attention and appreciation first! The easiest way is to fork the repo, add materials to the markdown files and submit a pull request. Also, you can submit an issue, write materials to us, and we can help you add them.
